DjangoStuff/CurriculumProject/CurriculumProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('tutorialApp/', include('tutorialApp.urls')),
    path('admin/', admin.site.urls),
]

DjangoStuff/CurriculumProject/tutorialApp/urls.py
from django.urls import path

from . import views

app_name = 'tutorialApp'

urlpatterns = [
    # default url
    path('', views.index, name='index'),

    # /tutorialApp/<int::company_id>/ number is the ID of the company
    path('<int:company_id>/',views.detail,name='detail'),
]

DjangoStuff/CurriculumProject/tutorialApp/models.py
from django.db import models

# Create your models here.

class Company(models.Model):
    name = models.CharField(max_length=150)
    logo = models.CharField(max_length=1000)
    location = models.CharField(max_length=1000)
    #makes it so then when printing, it prints its name and location
    def __str__(self):
        return self.name+' - '+self.location

class Product(models.Model):
    def __str__(self):
        return self.productName
    productName=models.CharField(max_length=1000)
    company=models.ForeignKey(Company, on_delete=models.CASCADE)
    image = models.CharField(max_length=1000)
    price = models.DecimalField(max_digits=8,decimal_places=2)

DjangoStuff/CurriculumProject/tutorialApp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Company

def index(request):
    all_companies = Company.objects.all();
    return render(request,'tutorialApp/index.html',{'all_companies':all_companies})

def detail(request,company_id):
    #try:
    #    company = Company.objects.get(id=company_id)
    #except Company.DoesNotExist:
    #    raise Http404("Company does not exist!")
    #return render(request,'tutorialApp/detail.html',{'company' : company})

    #same code as above, but cleaner

    company=get_object_or_404(Company, id=company_id)
    return render(request,'tutorialApp/detail.html',{'company' : company})

DjangoStuff/CurriculumProject/tutorialApp/templates/tutorialApp/detail.html
<img src="{{company.logo}}">
<h1>{{ company }}</h1>
<h3>Product List:</h3>
<ul>
  {%for product in company.product_set.all %}
  <li>{{product.productName}} - ${{product.price}}</li>
  {% endfor %}
</ul>

DjangoStuff/CurriculumProject/tutorialApp/templates/tutorialApp/index.html
{%if all_companies %}<!-- python code!-->
<!-- very simple list template-->
  <h1>Companies List</h1>
  <ul>
    {%for company in all_companies %}
    <li><a href="{%url 'tutorialApp:detail' company.id%}">{{ company.name }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <<h3>No companies added!</h3>
{% endif %}